security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        entity_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: false
            pattern: ^/
            logout: 
                path: app_logout
            guard:
                entry_point: App\Controller\AuthController
                authenticators:
                    - App\Security\UserAuthenticator
                    - App\Security\JwtAuthenticator
    access_control:
        - { path: ^/user/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/api/auth, role: IS_AUTHENTICATED_ANONYMOUSLY }